apiVersion: apps/v1
kind: Deployment
metadata:
  name: auxiliary-service
  namespace: auxiliary-service
spec:
  imagePullSecrets:
    - name: ecr-registry
  replicas: 1
  selector:
    matchLabels:
      app: auxiliary-service
  template:
    metadata:
      labels:
        app: auxiliary-service
    spec:
      containers:
      - name: auxiliary-service
        image: 058264106614.dkr.ecr.us-east-1.amazonaws.com/auxiliary-service:45a42a4
        ports:
        - containerPort: 8000
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          value: "us-east-1"