apiVersion: apps/v1
kind: Deployment
metadata:
  name: auxiliary-service
  namespace: auxiliary-service
spec:
  imagePullSecrets:
    - name: ecr-registry
  replicas: 1
  selector:
    matchLabels:
      app: auxiliary-service
  template:
    metadata:
      labels:
        app: auxiliary-service
    spec:
      containers:
      - name: auxiliary-service
        image: 211125350155.dkr.ecr.us-east-1.amazonaws.com/auxiliary-service:9813dfd
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config