apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: auxiliary-service
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVEzRUdQV1ozSElTS0dWNjY=
  AWS_SECRET_ACCESS_KEY: QXJ2RUZHcTBvamU3YjhZaytqNk1laStKcmZuUG9oNk5sUHFVQU5WZA==
