apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auxiliary-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: argocd.argoproj.io/instance=auxiliary-service 
  namespaceSelector:
    matchNames:
      - auxiliary-service
  endpoints:
    - port: 8000
      path: /metrics
      interval: 15s
