apiVersion: v1
kind: Service
metadata:
  name: auxiliary-service
  namespace: auxiliary-service
spec:
  selector:
    app: auxiliary-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: metrics
      port: 8000
      targetPort: 8000
  type: ClusterIP