apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:le1t0ftw/kantox-challenge-ldv.git"
    path: kubernetes/services
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true