apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/tu-usuario/tu-repo-k8s"
    path: k8s/base
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true