apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Monitoring
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: "git@github.com:le1t0ftw/kantox-challenge-ldv.git"
    path: kubernetes/argo-apps/monitoring
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true