apiVersion: apps/v1
kind: Deployment
metadata:
  name: auxiliary-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auxiliary-service
  template:
    metadata:
      labels:
        app: auxiliary-service
    spec:
      containers:
      - name: auxiliary-service
        image: 637423394741.dkr.ecr.us-east-1.amazonaws.com/auxiliary-service:78a097b
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
