apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-api
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-api
  template:
    metadata:
      labels:
        app: main-api
    spec:
      containers:
      - name: main-api
        image: myrepo/main-api:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config