apiVersion: apps/v1
kind: Deployment
metadata:
  name: auxiliary-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auxiliary-service
  template:
    metadata:
      labels:
        app: auxiliary-service
    spec:
      containers:
      - name: auxiliary-service
        image: le1t0ftw/aux:1.1
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
