apiVersion: v1
kind: Service
metadata:
  name: auxiliary-service
  namespace: microservices
spec:
  selector:
    app: auxiliary-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP