apiVersion: v1
kind: Service
metadata:
  name: main-api
  namespace: microservices
spec:
  selector:
    app: main-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP