apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-api
  namespace: main-api
spec:
  imagePullSecrets:
    - name: ecr-registry
  replicas: 1
  selector:
    matchLabels:
      app: main-api
  template:
    metadata:
      labels:
        app: main-api
    spec:
      containers:
      - name: main-api
        image: 058264106614.dkr.ecr.us-east-1.amazonaws.com/main-api:45a42a4
        ports:
        - containerPort: 8001
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: app-config