apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-api
  namespace: main-api
spec:
  imagePullSecrets:
    - name: ecr-registry
  replicas: 1
  selector:
    matchLabels:
      app: main-api
  template:
    metadata:
      labels:
        app: main-api
    spec:
      containers:
      - name: main-api
        image: 381492006952.dkr.ecr.us-east-1.amazonaws.com/main-api:32c89c6
        ports:
        - containerPort: 8000
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: app-config