apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: main-api-monitor
  namespace: main-api
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: main-api 
  namespaceSelector:
    matchNames:
      - main-api
  endpoints:
    - port: "8000"
      path: /metrics
      interval: 15s
