apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: main-api-monitor
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - main-api
  selector:
    matchLabels:
      app: main-api
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
