apiVersion: v1
kind: Service
metadata:
  name: main-api
  namespace: main-api
spec:
  selector:
    app: main-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8085
    - name: metrics
      protocol: TCP
      port: 9000
      targetPort: 8000
  type: ClusterIP
