apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: main-api-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: main-api  # Este label debe coincidir con el Service que expone métricas
  namespaceSelector:
    matchNames:
      - main-api
  endpoints:
    - port: 8000
      path: /metrics
      interval: 15s
