apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:le1t0ftw/kantox-challenge-ldv.git"
    targetRevision: main
    path: kubernetes/services/main-api
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
