---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
    destination:
      namespace: monitoring
      server: https://kubernetes.default.svc
    project: ansv  
    source:
      repoURL: https://github.com/prometheus-community/helm-charts.git
      path: charts/kube-prometheus-stack/crds/
      targetRevision: kube-prometheus-stack-31.0.0
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
      - Replace=true