apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/prometheus-operator/prometheus-operator'
    chart: kube-prometheus-stack
    targetRevision: 45.17.0
    helm:
      values: |
        alertmanager:
          enabled: true
        server:
          enabled: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true